import type { Author, Comment, News, NotificationDisplay, PinProfile, ProfileType, Question, ResearchItem, ResearchUpdate } from 'oa-shared';
export declare const fakeAuthorSB: (authorOverloads?: Partial<Author>) => Author;
export declare const createFakeCommentsSB: (numberOfComments?: number, commentOverloads?: {}) => Comment[];
export declare const fakeCommentSB: (commentOverloads?: Partial<Comment>) => Comment;
export declare const fakeNewsSB: (newsOverloads?: Partial<News>) => News;
export declare const fakeDisplayNotification: (notificationOverloads?: Partial<NotificationDisplay>) => NotificationDisplay;
export declare const fakeQuestionSB: (questionOverloads?: Partial<Question>) => Question;
export declare const fakeResearchItem: (researchItemOverloads?: Partial<ResearchItem>) => ResearchItem;
export declare const fakeResearchUpdate: (researchItemOverloads?: Partial<ResearchUpdate>) => ResearchUpdate;
export declare const fakeProfileType: (profileTypeOverLoads?: Partial<ProfileType>) => ProfileType;
export declare const fakePinProfile: (pinProfileOverLoads?: Partial<PinProfile>) => PinProfile;
