import { CommentDisplay } from './CommentDisplay';
import type { Meta, StoryFn } from '@storybook/react-vite';
declare const _default: Meta<typeof CommentDisplay>;
export default _default;
export declare const Default: StoryFn<typeof CommentDisplay>;
export declare const Editable: StoryFn<typeof CommentDisplay>;
export declare const Edited: StoryFn<typeof CommentDisplay>;
export declare const LongText: StoryFn<typeof CommentDisplay>;
export declare const ShortTextWithLink: StoryFn<typeof CommentDisplay>;
export declare const UserVotedUseful: StoryFn<typeof CommentDisplay>;
