import { ButtonShowReplies } from './ButtonShowReplies';
import type { Meta, StoryFn } from '@storybook/react-vite';
declare const _default: Meta<typeof ButtonShowReplies>;
export default _default;
export declare const DefaultComponent: () => import("react/jsx-runtime").JSX.Element;
export declare const Default: StoryFn<typeof ButtonShowReplies>;
export declare const RepliesShowing: StoryFn<typeof ButtonShowReplies>;
export declare const OneReply: StoryFn<typeof ButtonShowReplies>;
export declare const NoReplies: StoryFn<typeof ButtonShowReplies>;
export declare const NoCreatorName: StoryFn<typeof ButtonShowReplies>;
