import { ImageGalleryThumbnail } from './ImageGalleryThumbnail';
import type { Meta, StoryFn } from '@storybook/react-vite';
declare const _default: Meta<typeof ImageGalleryThumbnail>;
export default _default;
export declare const Default: StoryFn<typeof ImageGalleryThumbnail>;
export declare const AllowPortrait: StoryFn<typeof ImageGalleryThumbnail>;
export declare const DisallowPortrait: StoryFn<typeof ImageGalleryThumbnail>;
export declare const ImageIsActive: StoryFn<typeof ImageGalleryThumbnail>;
export declare const ImageIsNotActive: StoryFn<typeof ImageGalleryThumbnail>;
export declare const ThumbnailUrlInvalidAltText: StoryFn<typeof ImageGalleryThumbnail>;
export declare const ThumbnailUrlInvalidNameText: StoryFn<typeof ImageGalleryThumbnail>;
