import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ContentImageLightbox } from './ContentImageLightbox';
export default {
    title: 'Layout/ContentImageLightbox',
    component: ContentImageLightbox,
};
const sampleImages = [
    'https://picsum.photos/id/29/800/600',
    'https://picsum.photos/id/50/800/600',
    'https://picsum.photos/id/110/800/600',
];
export const Default = () => (_jsx(ContentImageLightbox, { children: _jsxs("div", { children: [_jsx("h2", { children: "Sample Content with Images" }), _jsx("p", { children: "Click on any image to open the lightbox view." }), _jsx("img", { src: sampleImages[0], alt: "Sample image 1", style: { maxWidth: '100%', marginBottom: '1rem' } }), _jsx("p", { children: "This is some text between images." }), _jsx("img", { src: sampleImages[1], alt: "Sample image 2", style: { maxWidth: '100%', marginBottom: '1rem' } })] }) }));
export const MultipleImages = () => (_jsx(ContentImageLightbox, { children: _jsxs("div", { children: [_jsx("h2", { children: "Multiple Images" }), _jsx("p", { children: "Navigate through multiple images using the lightbox controls." }), _jsx("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1rem' }, children: sampleImages.map((src, index) => (_jsx("img", { src: src, alt: `Sample image ${index + 1}`, style: { maxWidth: '100%' } }, index))) })] }) }));
export const WithRichContent = () => (_jsx(ContentImageLightbox, { children: _jsxs("article", { style: { maxWidth: '800px', margin: '0 auto', padding: '1rem' }, children: [_jsx("h1", { children: "Article with Images" }), _jsx("p", { children: "This demonstrates how the ContentImageLightbox component works with rich content containing multiple images throughout the text." }), _jsx("img", { src: sampleImages[0], alt: "Hero image", style: { maxWidth: '100%', marginBottom: '1rem' } }), _jsx("h2", { children: "Section 1" }), _jsx("p", { children: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." }), _jsx("img", { src: sampleImages[1], alt: "Section image", style: { maxWidth: '100%', margin: '1rem 0' } }), _jsx("h2", { children: "Section 2" }), _jsx("p", { children: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat." }), _jsx("img", { src: sampleImages[2], alt: "Another image", style: { maxWidth: '100%', marginTop: '1rem' } })] }) }));
export const CustomSelector = () => (_jsx(ContentImageLightbox, { selector: ".lightbox-image", children: _jsxs("div", { children: [_jsx("h2", { children: "Custom Selector Example" }), _jsx("p", { children: "Only images with the \"lightbox-image\" class will open in the lightbox." }), _jsx("img", { src: sampleImages[0], alt: "Lightbox enabled", className: "lightbox-image", style: { maxWidth: '100%', marginBottom: '1rem' } }), _jsx("p", { children: "This image below will NOT open in lightbox (no class):" }), _jsx("img", { src: sampleImages[1], alt: "No lightbox", style: { maxWidth: '100%', opacity: 0.5 } })] }) }));
